#!/bin/bash
#https://github.com/Anachron/i3blocks/blob/master/blocks/weather
# Based on http://openweathermap.org/current

API_KEY="1ce4dc0555abc2db81838896ad5f90b9"

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""
ICON_WIND=""

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WIND=$(echo "${WEATHER_INFO}" | grep -o "speed\":[0-9]\+\(\.[0-9]\+\)" | awk -F ':' '{print $2}')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo ""
else
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${ICON_WIND}${WIND}km/h"
  echo ""
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
